### ISSUE TITLE
How let 'adb shell input swipe' support argument 'duration' when api level <= 18?

### ISSUE THREAD

**Issue by CallMeZack** [dtmilano/AndroidViewClient#166]
Problem: when api level <=18(4.3), the command 'adb shell input swipe' doesn't support the arg 'duration'('adb shell input swipe x1 y1 x2 y2 duration'), I can only use 'adb shell input swipe x1 y1 x2 y2',  which results that swipe's default speed is too fast for some devices, resulting in the devices did not response the commad 'adb shell input swipe' in testing an app.

So, is there some ways to solve this problem? 
Ps: I tried replacing the sh command 'input', but it didn't work.

**Comment by dtmilano** [comment]
The upcoming **Culebra Tester** backend, which supports API level >= 18, has a `steps` parameter that translates directly to duration. Each step execution is throttled to 5ms per step. So for a 100 steps, the swipe will take about 1/2 second to complete.
Unfortunately, for API < 18, the only solution would be to backport the `input` command. That's a shame because this constitutes ~ 25% of the devices out there (according to [Platform Versions](http://developer.android.com/about/dashboards/index.html#Platform)).

**Culebra Tester** was also mentioned as the solution for other issues, see #165, #170, #175.

**Comment by dtmilano** [comment]
**CulebraTester** provides a real-time point and click test recording through a web browser.
If you are interested in being part of the Private Beta please fill out [this form](http://goo.gl/forms/XJk4sLQOZq).
