### ISSUE TITLE
Unable to run Concertina

### ISSUE THREAD

**Issue by IgorGanapolsky** [dtmilano/AndroidViewClient#209]
Hello,
I am trying to run Concertina to test the notification bar.  However, Culebra errors out with:
> Request failed
error: Internal Server Error (500)
SERVER INTERNAL ERROR: Serve() returned a null response.

Do you know what causes it?

**Comment by dtmilano** [comment]
Can you describe the steps?

**Comment by IgorGanapolsky** [comment]
Sure:
1) Background Service is running, with notification icon in the notification bar
2) Click Concertina, start
3) Move the mouse pointer on that notification icon and click
4) Observe the crash

**Comment by dtmilano** [comment]
Are we talking about this **Concertina start**?

![screen shot 2016-10-25 at 15 54 27](https://cloud.githubusercontent.com/assets/982482/19701943/8d3a793e-9acb-11e6-9fe1-ef100f86f9d4.png)

It should be disabled. Seems like a bug.

You can try the same without clicking **Concertina start**.

Thanks for reporting.

**Comment by IgorGanapolsky** [comment]
Yes, we are talking about **Concertina start**.  Is that an active feature?

**Comment by dtmilano** [comment]
It's not active. I think it makes sense to wait until all the generated code is stable before enabling it.

BTW, one thing you mentioned caught my attention and I guess it's worth clarifying it.
[Concertina mode](http://dtmilano.blogspot.ca/2015/08/culebra-concertina-mode.html) as explained, instead of sending pseudo-random events (a la monkey), analyzes the content of the screen and randomly selects a suitable event or action for the also randomly selected target, normally a View.
Then, clicking on the device after starting this mode should have no effect (if it has is a bug).

**Comment by IgorGanapolsky** [comment]
Yes, we are talking about **Concertina start**.  Is that an active feature?
